openapi: 3.0.1
info:
  title: starwars
  description: ''
  version: v2
servers:
  - url: https://apim-29112022-dev.azure-api.net/starwars/v2
paths:
  /people:
    get:
      summary: GetPeople
      operationId: getpeople
      responses:
        '200':
          description: 
  '/people/{id}':
    get:
      summary: GetPeopleById
      operationId: getpeoplebyid
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]